apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# KNative
- ../common/knative/knative-serving/overlays/gateways
- ../common/knative/knative-eventing/base
- ../common/istio-1-11/cluster-local-gateway/base

# Kubeflow namespace
- ../common/kubeflow-namespace/base

# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-11/kubeflow-istio-resources/base
