apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# Kubeflow namespace
- ../common/kubeflow-namespace/base

# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-11/kubeflow-istio-resources/base
